/* The following code was generated by JFlex 1.3.5 on 20/10/15 03:03 */

package if688;

import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;

 

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 20/10/15 03:03 from the specification file
 * <tt>file:/C:/Users/Nymeria/Documents/Workspace/MiniJava/minijava.flex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\5\1\10\25\0\1\5\1\27\3\0\1\24\1\30\1\0"+
    "\1\12\1\13\1\7\1\22\1\21\1\23\1\4\1\6\1\2\11\3"+
    "\1\0\1\11\1\25\1\20\1\26\2\0\22\1\1\56\7\1\1\16"+
    "\1\0\1\17\1\0\1\1\1\0\1\34\1\40\1\32\1\46\1\42"+
    "\1\53\1\57\1\52\1\41\2\1\1\33\1\55\1\45\1\50\1\36"+
    "\1\1\1\54\1\35\1\44\1\37\1\47\1\51\1\43\1\60\1\1"+
    "\1\14\1\31\1\15\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    49,    98,   147,   196,    49,    49,   245,    49,    49, 
       49,    49,    49,    49,    49,    49,   294,    49,    49,    49, 
       49,   343,   392,   441,   490,   539,   588,   637,   686,   735, 
      784,   833,   882,   931,   980,  1029,  1078,  1127,  1176,  1225, 
     1274,  1323,  1372,  1421,    49,    49,    49,    49,    49,    98, 
     1470,  1519,  1568,  1617,  1666,  1715,    98,  1764,  1813,  1862, 
     1911,  1960,  2009,  2058,  2107,  2156,  2205,  2254,  2303,  1323, 
     2352,  2401,  2450,  2499,  2548,  2597,  2646,    98,  2695,  2744, 
     2793,  2842,    98,  2891,  2940,  2989,  3038,  3087,  3136,  3185, 
       49,  3234,  3283,  3332,  3381,  3430,  3479,    98,  3528,    98, 
       98,    98,  3577,  3626,  3675,    98,  3724,  3773,    49,    98, 
     3822,  3871,  3920,  3969,  4018,    98,    98,  4067,  4116,  4165, 
       98,    98,    98,  4214,  4263,    98,    98,  4312,    98,    98, 
     4361,  4410,  4459,  4508,  4557,  4606,  4655,  4704,  4753,  4802, 
     4851,    49
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\7\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\3\1\35\1\36\1\3"+
    "\1\37\1\40\1\41\1\3\1\42\1\43\1\3\1\44"+
    "\1\3\1\45\1\3\1\46\1\47\1\50\1\51\2\3"+
    "\62\0\3\3\25\0\30\3\4\0\1\52\56\0\2\5"+
    "\1\52\62\0\1\53\1\54\71\0\1\55\60\0\1\56"+
    "\60\0\1\57\60\0\1\60\70\0\1\61\31\0\3\3"+
    "\25\0\1\62\27\3\1\0\3\3\25\0\2\3\1\63"+
    "\25\3\1\0\3\3\25\0\11\3\1\64\16\3\1\0"+
    "\3\3\25\0\13\3\1\65\14\3\1\0\3\3\25\0"+
    "\6\3\1\66\21\3\1\0\3\3\25\0\17\3\1\67"+
    "\10\3\1\0\3\3\25\0\14\3\1\70\5\3\1\71"+
    "\5\3\1\0\3\3\25\0\2\3\1\72\7\3\1\73"+
    "\15\3\1\0\3\3\25\0\21\3\1\74\1\3\1\75"+
    "\4\3\1\0\3\3\25\0\11\3\1\76\16\3\1\0"+
    "\3\3\25\0\17\3\1\77\10\3\1\0\3\3\25\0"+
    "\21\3\1\100\6\3\1\0\3\3\25\0\3\3\1\101"+
    "\24\3\1\0\3\3\25\0\11\3\1\102\16\3\1\0"+
    "\3\3\25\0\3\3\1\103\24\3\1\0\3\3\25\0"+
    "\13\3\1\104\13\3\1\105\2\0\2\106\55\0\7\107"+
    "\1\0\51\107\7\110\1\0\51\110\1\0\3\3\25\0"+
    "\3\3\1\111\24\3\1\0\3\3\25\0\14\3\1\112"+
    "\13\3\1\0\3\3\25\0\3\3\1\113\24\3\1\0"+
    "\3\3\25\0\7\3\1\114\20\3\1\0\3\3\25\0"+
    "\17\3\1\115\10\3\1\0\3\3\25\0\13\3\1\116"+
    "\14\3\1\0\3\3\25\0\4\3\1\117\23\3\1\0"+
    "\3\3\25\0\13\3\1\120\14\3\1\0\3\3\25\0"+
    "\10\3\1\121\17\3\1\0\3\3\25\0\6\3\1\122"+
    "\21\3\1\0\3\3\25\0\20\3\1\123\7\3\1\0"+
    "\3\3\25\0\10\3\1\124\17\3\1\0\3\3\25\0"+
    "\10\3\1\125\17\3\1\0\3\3\25\0\2\3\1\126"+
    "\25\3\1\0\3\3\25\0\13\3\1\127\14\3\1\0"+
    "\3\3\25\0\10\3\1\130\17\3\1\0\3\3\25\0"+
    "\23\3\1\131\4\3\1\0\3\3\25\0\4\3\1\132"+
    "\23\3\10\107\1\133\50\107\7\110\1\134\51\110\1\0"+
    "\3\3\25\0\4\3\1\135\23\3\1\0\3\3\25\0"+
    "\26\3\1\136\1\3\1\0\3\3\25\0\13\3\1\137"+
    "\14\3\1\0\3\3\25\0\2\3\1\140\25\3\1\0"+
    "\3\3\25\0\2\3\1\141\25\3\1\0\3\3\25\0"+
    "\11\3\1\142\16\3\1\0\3\3\25\0\11\3\1\143"+
    "\16\3\1\0\3\3\25\0\4\3\1\144\23\3\1\0"+
    "\3\3\25\0\11\3\1\145\16\3\1\0\3\3\25\0"+
    "\15\3\1\146\12\3\1\0\3\3\25\0\2\3\1\147"+
    "\25\3\1\0\3\3\25\0\4\3\1\150\23\3\1\0"+
    "\3\3\25\0\6\3\1\151\21\3\1\0\3\3\25\0"+
    "\14\3\1\152\13\3\1\0\3\3\25\0\10\3\1\153"+
    "\17\3\1\0\3\3\25\0\13\3\1\154\14\3\6\110"+
    "\1\155\1\134\51\110\1\0\3\3\25\0\4\3\1\156"+
    "\23\3\1\0\3\3\25\0\13\3\1\157\14\3\1\0"+
    "\3\3\25\0\10\3\1\160\17\3\1\0\3\3\25\0"+
    "\10\3\1\161\17\3\1\0\3\3\25\0\11\3\1\162"+
    "\16\3\1\0\3\3\25\0\14\3\1\163\13\3\1\0"+
    "\3\3\25\0\11\3\1\164\16\3\1\0\3\3\25\0"+
    "\11\3\1\165\16\3\1\0\3\3\25\0\23\3\1\166"+
    "\4\3\1\0\3\3\25\0\14\3\1\167\13\3\1\0"+
    "\3\3\25\0\11\3\1\170\16\3\1\0\3\3\25\0"+
    "\21\3\1\171\6\3\1\0\3\3\25\0\1\3\1\172"+
    "\26\3\1\0\3\3\25\0\1\3\1\173\26\3\1\0"+
    "\3\3\25\0\3\3\1\174\24\3\1\0\3\3\25\0"+
    "\15\3\1\175\12\3\1\0\3\3\25\0\14\3\1\176"+
    "\13\3\1\0\3\3\25\0\26\3\1\177\1\3\1\0"+
    "\3\3\25\0\24\3\1\200\3\3\1\0\3\3\25\0"+
    "\14\3\1\201\13\3\1\0\3\3\25\0\4\3\1\202"+
    "\23\3\1\0\3\3\1\203\24\0\30\3\50\0\1\204"+
    "\47\0\1\205\65\0\1\206\20\0\1\207\112\0\1\210"+
    "\76\0\1\211\45\0\1\212\64\0\1\213\57\0\1\214"+
    "\47\0\1\215\72\0\1\216\13\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  1,  1,  9,  9,  1,  9,  9,  9,  9,  9,  9,  9,  9, 
     1,  9,  9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  0,  0,  9,  9,  9,  9, 
     9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  0,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[4900];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 2: 
        case 25: 
        case 26: 
        case 27: 
        case 28: 
        case 29: 
        case 30: 
        case 31: 
        case 32: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 83: 
        case 84: 
        case 85: 
        case 86: 
        case 87: 
        case 88: 
        case 89: 
        case 92: 
        case 93: 
        case 94: 
        case 95: 
        case 96: 
        case 98: 
        case 102: 
        case 103: 
        case 104: 
        case 106: 
        case 107: 
        case 110: 
        case 111: 
        case 112: 
        case 113: 
        case 114: 
        case 117: 
        case 118: 
        case 119: 
        case 123: 
        case 124: 
        case 127: 
          {  return symbolFactory.newSymbol("ID", ID);  }
        case 143: break;
        case 56: 
          {  return symbolFactory.newSymbol("IF", IF);  }
        case 144: break;
        case 69: 
          {  return symbolFactory.newSymbol("DOUBLE", DOUBLE, Double.parseDouble(yytext()));  }
        case 145: break;
        case 3: 
        case 4: 
          {  return symbolFactory.newSymbol("NUMBER", NUMBER, Integer.parseInt(yytext()));  }
        case 146: break;
        case 108: 
          {  /* Ignorar Comment */  }
        case 147: break;
        case 90: 
          {  System.out.println("Illegal Token '" + yytext() 
                    + "' line: " + yyline + ", column: " + yycolumn);  }
        case 148: break;
        case 129: 
          {  return symbolFactory.newSymbol("EXTENDS", EXTENDS);  }
        case 149: break;
        case 128: 
          {  return symbolFactory.newSymbol("BOOLEAN", BOOLEAN);  }
        case 150: break;
        case 116: 
          {  return symbolFactory.newSymbol("FALSE", BOOLCONST);  }
        case 151: break;
        case 100: 
          {  return symbolFactory.newSymbol("TRUE", BOOLCONST);  }
        case 152: break;
        case 141: 
          {  return symbolFactory.newSymbol("PRINT", PRINT);  }
        case 153: break;
        case 115: 
          {  return symbolFactory.newSymbol("WHILE", WHILE);  }
        case 154: break;
        case 109: 
          {  return symbolFactory.newSymbol("CLASS", CLASS);  }
        case 155: break;
        case 17: 
          {  return symbolFactory.newSymbol("COMMA", COMMA);  }
        case 156: break;
        case 12: 
          {  return symbolFactory.newSymbol("BEGIN", BEGIN);  }
        case 157: break;
        case 8: 
          {  return symbolFactory.newSymbol("TIMES", TIMES);  }
        case 158: break;
        case 19: 
          {  return symbolFactory.newSymbol("MINUS", MINUS);  }
        case 159: break;
        case 48: 
          {  return symbolFactory.newSymbol("AND", BBINOP);  }
        case 160: break;
        case 120: 
          {  return symbolFactory.newSymbol("LEN", LEN);  }
        case 161: break;
        case 13: 
          {  return symbolFactory.newSymbol("END", END);  }
        case 162: break;
        case 5: 
          {  return symbolFactory.newSymbol("DOT", DOT);  }
        case 163: break;
        case 20: 
          {  return symbolFactory.newSymbol("MOD", MOD);  }
        case 164: break;
        case 21: 
          {  return symbolFactory.newSymbol("LE", COMP);  }
        case 165: break;
        case 22: 
          {  return symbolFactory.newSymbol("GT", COMP);  }
        case 166: break;
        case 44: 
          {  return symbolFactory.newSymbol("EQ", COMP);  }
        case 167: break;
        case 77: 
          {  return symbolFactory.newSymbol("INT", INT);  }
        case 168: break;
        case 82: 
          {  return symbolFactory.newSymbol("NEW", NEW);  }
        case 169: break;
        case 6: 
          {  /* Ignorar whitespace. */  }
        case 170: break;
        case 105: 
          {  return symbolFactory.newSymbol("MAIN", MAIN);  }
        case 171: break;
        case 101: 
          {  return symbolFactory.newSymbol("VOID", VOID);  }
        case 172: break;
        case 18: 
          {  return symbolFactory.newSymbol("PLUS", PLUS);  }
        case 173: break;
        case 15: 
          {  return symbolFactory.newSymbol("RBRA", RBRA);  }
        case 174: break;
        case 14: 
          {  return symbolFactory.newSymbol("LBRA", LBRA);  }
        case 175: break;
        case 1: 
        case 24: 
          {  throw new Error("Caractere ilegal <"+yytext()+">");  }
        case 176: break;
        case 9: 
          {  return symbolFactory.newSymbol("SEMI", SEMI);  }
        case 177: break;
        case 23: 
          {  return symbolFactory.newSymbol("NOT", BUNOP);  }
        case 178: break;
        case 45: 
          {  return symbolFactory.newSymbol("LEQ", COMP);  }
        case 179: break;
        case 46: 
          {  return symbolFactory.newSymbol("GTD", COMP);  }
        case 180: break;
        case 47: 
          {  return symbolFactory.newSymbol("NEQ", COMP);  }
        case 181: break;
        case 49: 
          {  return symbolFactory.newSymbol("OR", BBINOP);  }
        case 182: break;
        case 97: 
          {  return symbolFactory.newSymbol("ELSE", ELSE);  }
        case 183: break;
        case 99: 
          {  return symbolFactory.newSymbol("THIS", THIS);  }
        case 184: break;
        case 126: 
          {  return symbolFactory.newSymbol("STRING", STRING);  }
        case 185: break;
        case 125: 
          {  return symbolFactory.newSymbol("RETURN", RETURN);  }
        case 186: break;
        case 122: 
          {  return symbolFactory.newSymbol("PUBLIC", PUBLIC);  }
        case 187: break;
        case 121: 
          {  return symbolFactory.newSymbol("STATIC", STATIC);  }
        case 188: break;
        case 16: 
          {  return symbolFactory.newSymbol("ASSIGN", ASSIGN);  }
        case 189: break;
        case 11: 
          {  return symbolFactory.newSymbol("RPAREN", RPAREN);  }
        case 190: break;
        case 10: 
          {  return symbolFactory.newSymbol("LPAREN", LPAREN);  }
        case 191: break;
        case 7: 
          {  return symbolFactory.newSymbol("DIVIDE", DIVIDE);  }
        case 192: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, i.e. it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          scanner = new Lexer( new java.io.FileReader(argv[i]) );
          while ( !scanner.yy_atEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
